### ISSUE TITLE
Pre-Select Checkbox when i get data from Infinity datasource

### ISSUE THREAD

**Issue by skynet-05** [VolkovLabs/business-forms#443]
Considering this my response
```
[
	{
		"value": "12345",
		"label": "foo",
		"isChecked": true
	},
	...
]
```
Im using the form element: "Checkbox list with custom options"
How do i pre-check the boxes as the data is fetched?

**Comment by vitPinchuk** [comment]
@skynet-05 Thank you for your question

Are you having an issue with the initial value for the `Checkbox list with custom options`? 
Do you set the initial value but it doesn't work for your `Checkbox list`? 
We fixed that in a similar issue #428 and #435
It should work correctly from version 4.1.0

Or are you trying to figure out how to set the initial value for `Checkbox list` using the Infinity data source as a whole? 

Thank you.

**Comment by skynet-05** [comment]
No, I'm able to see the checkboxes once the data is fetched from the datasource but is there an option to automatically select the checkboxes when for certain is mapped as checked = true

> Considering this my response
> 
> ```
> [
> 	{
> 		"value": "12345",
> 		"label": "foo",
> 		"isChecked": true
> 	},
> 	...
> ]
> ```
> 
> Im using the form element: "Checkbox list with custom options" How do i pre-check the boxes as the data is fetched?

if my data sends `isChecked = true` I want this particular value to be preselected, so that i can have an option to unselect and update the values.

**Comment by vitPinchuk** [comment]
@skynet-05 Thank you for your question and the detailed information. 

We have added a few updates to our documentation to clarify moments related to setting initial values and mapping them to form elements. 
The updates will be available shortly. 

We have added some changes to our panel. The `Field` and `Query Field` ([Query](https://volkovlabs.io/plugins/volkovlabs-form-panel/data-flow/#query)) fields will be placed in the `Initial Query` section in the options. The updates will be available since 4.2.0 version. 

Basic issue. To set initial values via Infinity Data source and another type of data source, please, use `Query Field` option in element. Please select `Initial Action` to `Query`, after that Select a field from the `Query` response and it should automatically preselect values. 

`Initial Action`  Section
![image](https://github.com/user-attachments/assets/cb08ea69-8fcb-44ce-be32-85f528df7c92)


 `Query` Fields
![image](https://github.com/user-attachments/assets/c5d71d49-4abd-4bc1-8d05-5568a6ea8eca)

**Comment by skynet-05** [comment]
Hey,
Thank you for your update regarding this.
I'm still facing few issue w.r.t. this. Let me reiterate the issue again.

```
[
	{
		"_id": "12345",
		"lable": "foo",
		"isChecked": true
	},
    {
		"_id": "123456",
		"label": "foo",
		"isChecked": false
	},
	...
]
```
Considering the above response from my API using infinity plugin
This is what i see in my panel

![image](https://github.com/user-attachments/assets/5f1b9b06-60f7-47a5-be22-4ad3dc1cb4cd)
and below are the configurations

![image](https://github.com/user-attachments/assets/521ade08-7145-4a8d-9774-e461d83a5ce6)

![image](https://github.com/user-attachments/assets/b3126819-da55-4191-8459-9222a64fbf4f)

But with the above configurations, for the initial checkbox selections its only pre selecting the last ones

Current version of Business Form is `4.3.1`

Do let me know if I have to update the way i send API response or i misconfigured something

Thank you :)
